#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect the requirements
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

# allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Creating index
echo "Hello World!" | sudo tee /var/www/html/index.html

# variable containing string and directive

#string_rep="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

# use sed to replace text

#sudo sed -i "s/server_name _;/$string_rep/" /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
# restart the nginx service
sudo service nginx restart
