#!/usr/bin/env bash
# Bash script that configures a server Nginx port 8080 to listen to port 80
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
