#!/usr/bin/env bash
# Bash Script that displays "Best School" 10 times, but for the 9th time print Hi.

i=0

while [ $i -le 10 ]
do
   echo "Best School"
       if [ $i -eq 9 ]; then
          echo "Hi"
       fi
       ((i++))
done
