#!/usr/bin/env bash
# Bash script that configures the container to fit the above requirements
sudo sed -i 's/user www-data/user nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conif
pkill apache2
sudo -u nginx service nginx restart
