#!/usr/bin/env bash
# Previous task, but in 7 or less lines
sudo sed -i 's/user www-data/user nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conif
pkill apache2
sudo -u nginx service nginx restart
